### ISSUE TITLE
No results Il Corsaro Nero [KeyError: 'movie_extra2']

### ISSUE THREAD

**Issue by castiman** [elgatito/script.elementum.burst#105]
Hello @elgatito,
I've tried to use "Il Corsaro Nero" as provider, but no results and on screen appear the notification: "Provider" too slow.
This is the log:
`00:46:31.260 T:20234  NOTICE: [script.elementum.burst] Burstin' with Il Corsaro Nero
00:46:31.275 T:20237   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.elementum.burst/burst/burst.py", line 545, in run_provider
                                                filterInstance.use_movie(provider, payload)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.elementum.burst/burst/filtering.py", line 217, in use_movie
                                                self.extras.append("%s" % definition['movie_extra2'] if definition['movie_extra2'] else '')
                                            KeyError: 'movie_extra2'`
So I've tried to edit providers.json in this way:
- "movie_keywords": "{title:it} {year}",
- "movie_keywords2": "{title:original} {year}",
+"movie_keywords": "{title:original} {year}",
and finally it's works! (Is that the right choice?)
Can I ask you why that second parameter was added? What's that supposed to do?

Thanks!

**Comment by guglicap** [comment]
Not the owner, but I've been tinkering with this plugin for a while now and I think I figured it out. The "2" variants of searches, see also `tv_keywords2` or `season_keywords2`, are just other searches the script performs. It's pretty clear how this works with `tv_keywords`, which is used to search tv shows *episodes*, if you have a look you'll see most providers will have something like this 
```
        "tv_keywords": "{title:original} s{season:2}e{episode:2}",
        "tv_keywords2": "{title:original} s{season:2}"
```
basically, what that that does is searching for the single episode AND the whole season, so that if the single episode isn't found, maybe it can find the whole season (which of course contains the episode).

In your case, `ilcorsarenero` is using this to search for the italian version of the movie as well as the original version (which imo, is kind of stupid since we already have plenty of english providers). The "correct" fix would be to add a `movie_extra2: ""` line, anyway. What you're doing right now is making it search for original versions only.

**Comment by castiman** [comment]
Today after some queries to the provider I understand that we need to search with both titles, because unfortunately sometimes they are loaded with the Italian title and others with the original title.
So after, I realized I did a foolishness in leaving only the original title, I checked that the error is only in the missing parameter: `""movie_extra2": "",`(that I initially confused with "movie_keywords2" and I didn't understand the error log)

**Comment by guglicap** [comment]
What's that whole "sometimes it's loaded with the English title sometimes with the Italian one" thing? That's super weird, could you provide an example? I'm genuinely curious. Does it happen on the website as well?

**Comment by castiman** [comment]
Yes it happen also on the website e.g. the first movie on Trending list (Ralph).
If you try to search with English title no results, otherwise 2 result with Italian title.

**Comment by guglicap** [comment]
Yeah, but that's normal, since ilcorsaronero is Italian only. IMO, we should leave the title: it lines only as that will be the Italian title if there is a translation (Ralph, for example) or the original title if there is none (Inception comes to mind)

**Comment by elgatito** [comment]
@castiman if you want to search both languages, you have to define few queries:
```
"tv_keywords": "{title:it} s{season:2}e{episode:2}",
"tv_keywords2": "{title:original} s{season:2}e{episode:2}"
```

**Comment by elgatito** [comment]
Closing this issue. 
New issues should come in separate issues.
