### ISSUE TITLE
torrentgalaxy almost always times out

### ISSUE THREAD

**Issue by gitlaman** [elgatito/script.elementum.burst#399]
As the title says, torrentgalaxy.to almost always times out, sometimes it gives results but not always.

From my phone i can open the page but when i search i must enter captcha code first, maybe that is the reason for the timeout in burst plugin.

Can anyone help, is there something that i can do, because this site has the best torrents that i know of.

thepiratebay stopped giving results so also not working

Thanks in advance

**Comment by gitlaman** [comment]
Yes i understand, thanks for the info

**Comment by antonsoroko** [comment]
@elgatito just curious, what do you think about UI for entering captcha? :-)
I saw such UI in some pirating addon (THE CREW or Scrubs v2 or Fen) when i tested several addons, they used it to bypass captcha on some video hosting website, i think.

**Comment by antonsoroko** [comment]
@gitlaman burst was updated, so please update it and enable thepiratebay in settings.

**Comment by elgatito** [comment]
@antonsoroko 

> @elgatito just curious, what do you think about UI for entering captcha? :-)

It does not make sense, because format of Captcha is different and there is often Javascript involved into generation of fields/values to make it harder for automation. So in the end you would need a headless Chromium and a lot of manual work for each use case to avoid captcha or render/solve it. (Chromium is not avialable to all platform Elementum works on). That is the way Jackett solves Cloudflare issues, btw.

In my opinion it makes sense to avoid **getting catchas** at all, by re-using authentication session or cookies sharing. I will try this approach when I have some time for that.

**Comment by gitlaman** [comment]
> @gitlaman burst was updated, so please update it and enable thepiratebay in settings.

Thanks it is working now
