### ISSUE TITLE
Error when download torrent

### ISSUE THREAD

**Issue by vic1997** [elgatito/script.elementum.burst#94]
Hello, after searching for torrent (with the provider YGGtorrent), it return 0 result.
So I search in logs and i found this : 
https://pastebin.com/Snue6QB6

`Resolve failed for https://www2.yggtorrent.gg/engine/download_torrent?id=298805 : Decode error: bencode: syntax error (offset: 0): unknown value type 'V'`

Have you an idea why it make that ?
Because it found 2 torrent but bug at this moment.

Thank's in advance for response.

**Comment by elgatito** [comment]
I have seen this. 
Login to ygg does not work currently.

**Comment by elgatito** [comment]
Please, try 0.0.32.

**Comment by vic1997** [comment]
@elgatito Works ! Thank you ! I don't know what's wrong but you apparently found.
Thank you very much

**Comment by hegi25** [comment]
The bug is in the main elementum addon, not in burst. I downgraded it to the previous version and now it works.

**Comment by vic1997** [comment]
@hegi25 Why would it work without updating? Explain how you did it.

**Comment by sapiora** [comment]
I don't know if the issue is with Elementum (v 0.67) or Elementum Burst (v 0.32) but after the last update:
1) in the Settings of Elementum Burst when I select any providers from Public trackers and search movie/tv show, I get "Timed Out" notification and zero results. However with the Private trackers there is no issues. In order to not have issues I have to have selected only providers from Private trackers.

2) in the Settings of Elementum Burst when I try to scroll down in Private trackers I was able to go only from "0day" provider to "tfile.me" provider; when I scroll up from "0day" provider I am able to go to "XtremeZone" provider;

3) in the Settings of Elementum Burst when I select "Zelka" provider in Private trackers I get message "Are you sure you want to reset the settings in this category?".

**Comment by bibic123** [comment]
https://pastebin.com/ssGqmnfv

same here, Burst is finding torrents on YGGtorrent, but elementum can't download them, there's a problem with annoucing on the tracker as we can see on my log.

Can you please fix this issue Elgatito ? thanks, everything else works like a charm :)

**Comment by sapiora** [comment]
About issues No.1 and 2 from my previous post to work (somehow) in Elementum (v 0.0.68) Settings -> Proxy -> Enable built-in HTTP proxy should be disabled. However, this trick sometimes pull results, and sometimes "Timed out".

About issue No. 3 there is no change concerning Elementum Burst (v 0.0.32) Private trackers. Still can't scroll all the way down to all providers and still can't switch on/off Zelka ... still the same message.

@elgatito Please accept my Gratitude toward your hard efforts to make us happy with your add-ons. I appreciate it very much and I think we all do. The issues I am reporting are my way to try to contribute in making them perfect.
